site_name: when-exactly
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Core Concepts: tutorial/core-concepts.md
  - Year: tutorial/year.md
  - Moment: tutorial/moment.md
  - Delta: tutorial/delta.md
  - API: api.md
markdown_extensions:
  - admonition: {}
watch:
  - src/
plugins:
  - search
  - autorefs
  - mkdocstrings