site_name: when-exactly
theme:
  name: mkdocs
  color_mode: auto
nav:
  - Getting Started: getting-started.md
  - API Reference: api.md
  - Core Concepts:
    - Overview: core-concepts.md
    - Moment: api/moment.md
    - Delta: api/delta.md
    - Interval: api/interval.md
    - Collection: api/collection.md
    - Custom Interval: api/custom-interval.md
  - Intervals:
    - Year: api/year.md
    - Month: api/month.md
    - Week: api/week.md
    - Day: api/day.md
    - OrdinalDay: api/ordinal-day.md
    - Weekday: api/weekday.md
    - Hour: api/hour.md
    - Minute: api/minute.md
    - Second: api/second.md
  - Collections:
    - Years: api/years.md
    - Months: api/months.md
    - Weeks: api/weeks.md
    - Days: api/days.md
    - Weekdays: api/weekdays.md
    - Hours: api/hours.md
    - Minutes: api/minutes.md
    - Seconds: api/seconds.md
markdown_extensions:
  - admonition: {}
watch:
  - src/
plugins:
  - search
  - autorefs
  - mermaid2
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            # refer to https://mkdocstrings.github.io/python/reference/api/?h=docs#mkdocstrings_handlers.python.PythonInputOptions.docstring_style
            docstring_style: google # https://mkdocstrings.github.io/python/usage/configuration/docstrings/
            annotations_path: full
            inherited_members: true
            # members: true # uncomment to show all members by default
            show_root_toc_entry: false
