site_name: when-exactly
theme:
  name: mkdocs
  color_mode: auto
nav:
  - Getting Started: getting-started.md
  - Core Concepts: core-concepts.md
  - Year: tutorial/year.md
  - Moment: moment.md
  - Delta: tutorial/delta.md
  - API: api.md
markdown_extensions:
  - admonition: {}
watch:
  - src/
plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google # https://mkdocstrings.github.io/python/usage/configuration/docstrings/
            annotations_path: full
            inherited_members: true